/**
 * Order Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provides the information to calculate the fees. 
 */
export interface FeeInformation { 
    /**
     * Expiration date of the offered fee. Order service might not accept the fee after this expiration date. Encoded as ISO 8601 UTC. 
     */
    expirationDate?: string;
    /**
     * Amount of a token. uint256 encoded in decimal.
     */
    minimalFee?: string;
    /**
     * The fee ratio charged on a sellAmount. Denoted in basis points
     */
    feeRatio?: number;
}

