/**
 * Order Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderCancellationError { 
    errorType?: OrderCancellationError.ErrorTypeEnum;
    description?: string;
}
export namespace OrderCancellationError {
    export type ErrorTypeEnum = 'InvalidSignature' | 'InvalidOrderUid';
    export const ErrorTypeEnum = {
        InvalidSignature: 'InvalidSignature' as ErrorTypeEnum,
        InvalidOrderUid: 'InvalidOrderUid' as ErrorTypeEnum
    };
}


