/**
 * Order Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderPostError { 
    errorType?: OrderPostError.ErrorTypeEnum;
    description?: string;
}
export namespace OrderPostError {
    export type ErrorTypeEnum = 'MissingOrderData' | 'InvalidSignature' | 'DuplicateOrder' | 'InsufficientFunds';
    export const ErrorTypeEnum = {
        MissingOrderData: 'MissingOrderData' as ErrorTypeEnum,
        InvalidSignature: 'InvalidSignature' as ErrorTypeEnum,
        DuplicateOrder: 'DuplicateOrder' as ErrorTypeEnum,
        InsufficientFunds: 'InsufficientFunds' as ErrorTypeEnum
    };
}


