/**
 * Order Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * EIP712 signature of struct OrderCancellation { orderUid: bytes } from the order\'s owner 
 */
export interface OrderCancellation { 
    /**
     * 65 bytes encoded as hex with `0x` prefix. r + s + v from the spec.
     */
    signature?: object;
}

