/**
 * Order Book API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Is this a buy order or sell order?
 */
export type OrderType = 'buy' | 'sell';

export const OrderType = {
    Buy: 'buy' as OrderType,
    Sell: 'sell' as OrderType
};

